# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
