# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170628_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='emailId',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
