# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-22 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
