# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_auto_20170623_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='price',
        ),
    ]
